### ISSUE TITLE
Currencies without Symbol

### ISSUE THREAD

**Issue by fraadsbrandth** [smoketurner/dropwizard-money#1]
In the Constructor of MoneyModule the formatter is made hardcoded with CurrencyStyle.SYMBOL. But a lot of currencies without symbols, like Norwegian Kroners (NOK) that I am working with. This causes the deserialization to fail.

Have tested to create my own MoneyModule where only change is to set CurrencyStyle.CODE and then it all works fine.

Could this be a parameter in a constructor? Or a part of a Builder to create a MoneyModule?

**Comment by jplock** [comment]
Sorry for the late reply, just saw this issue now.  That's a good idea, let me see if I can fix that somehow.
